export const reasonCodes = {
  agentCashIn: "agent_cash_in",
  agentOps: "agent_ops",
  ambiguousMatch: "ambiguous_match",
  billerVerificationRequired: "biller_verification_required",
  credentialProtection: "credential_protection",
  criticalEscalation: "critical_escalation",
  delay: "delay",
  disputeInitiated: "dispute_initiated",
  duplicatePayment: "duplicate_payment",
  establishedRecipientPattern: "established_recipient_pattern",
  evidenceInconsistent: "evidence_inconsistent",
  insufficientData: "insufficient_data",
  merchantPolicyDependent: "merchant_policy_dependent",
  merchantSettlement: "merchant_settlement",
  needsClarification: "needs_clarification",
  paymentFailed: "payment_failed",
  pending: "pending",
  pendingTransaction: "pending_transaction",
  phishing: "phishing",
  potentialBalanceDeduction: "potential_balance_deduction",
  refundRequest: "refund_request",
  ruleBased: "rule_based",
  safeFallback: "safe_fallback",
  safetyGuardApplied: "safety_guard_applied",
  transactionMatch: "transaction_match",
  vagueComplaint: "vague_complaint",
  wrongTransfer: "wrong_transfer",
  wrongTransferClaim: "wrong_transfer_claim",
} as const;

export type ReasonCode = (typeof reasonCodes)[keyof typeof reasonCodes];

export const allowedReasonCodes = [
  reasonCodes.agentCashIn,
  reasonCodes.agentOps,
  reasonCodes.ambiguousMatch,
  reasonCodes.billerVerificationRequired,
  reasonCodes.credentialProtection,
  reasonCodes.criticalEscalation,
  reasonCodes.delay,
  reasonCodes.disputeInitiated,
  reasonCodes.duplicatePayment,
  reasonCodes.establishedRecipientPattern,
  reasonCodes.evidenceInconsistent,
  reasonCodes.insufficientData,
  reasonCodes.merchantPolicyDependent,
  reasonCodes.merchantSettlement,
  reasonCodes.needsClarification,
  reasonCodes.paymentFailed,
  reasonCodes.pending,
  reasonCodes.pendingTransaction,
  reasonCodes.phishing,
  reasonCodes.potentialBalanceDeduction,
  reasonCodes.refundRequest,
  reasonCodes.ruleBased,
  reasonCodes.safeFallback,
  reasonCodes.safetyGuardApplied,
  reasonCodes.transactionMatch,
  reasonCodes.vagueComplaint,
  reasonCodes.wrongTransfer,
  reasonCodes.wrongTransferClaim,
] as const;
